# Generated by Django 5.1.2 on 2024-10-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0007_alter_borrowing_expected_return_date'),
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='Borrowings.borrowing'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.TextField(max_length=255),
        ),
    ]
