# Generated by Django 5.1.2 on 2024-10-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_alter_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(max_length=500),
        ),
    ]
