# Generated by Django 5.1.2 on 2024-10-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_payment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
