# Generated by Django 5.1.2 on 2024-10-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='library',
        ),
    ]
