# Generated by Django 5.1.2 on 2024-10-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.PositiveIntegerField(),
        ),
    ]
