# Generated by Django 5.1.2 on 2024-10-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_tag_author_tags_book_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
