# Generated by Django 5.1.2 on 2024-10-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
