# Generated by Django 5.1.2 on 2024-10-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_inventory'),
        ('Borrowings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['borrow_date', 'user']},
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.ManyToManyField(to='Books.book'),
        ),
    ]
