# Generated by Django 5.1.2 on 2024-10-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_inventory'),
        ('Borrowings', '0003_alter_borrowing_options_remove_borrowing_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book',
            field=models.ManyToManyField(related_name='borrowings', to='Books.book'),
        ),
    ]
