# Generated by Django 5.1.2 on 2024-10-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0004_alter_borrowing_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book',
            new_name='books',
        ),
    ]
