# Generated by Django 5.1.2 on 2024-10-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0005_rename_book_borrowing_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-actual_return_date', '-borrow_date', 'user']},
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
