# Generated by Django 5.1.2 on 2024-10-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowings', '0006_alter_borrowing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateTimeField(),
        ),
    ]
