# Generated by Django 5.1.2 on 2024-10-16 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='subdomain',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
